name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Optional: build step, not needed for your static site
      # - run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: gh-pages
          folder: .

      - name: Cleanup temp folder (optional)
        run: git worktree remove github-pages-deploy-action-temp-deployment-folder --force
        continue-on-error: true
