name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy HTML application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npm install -g browserify

      - name: Bundle script with Browserify
        run: npx browserify script.js -o main.js

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/ci-cd:latest$(date-'%Y-%m-%d%H-%M-%S')

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/ci-cd:latest$(date-'%Y-%m-%d%H-%M-%S')
