name: CI/CD Pipeline # this is the name of the ci/cd pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy html application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies (including browserify)
        run: |
          npm install
          npm install -g browserify

      - name: Build files to support common modules
        run: browserify script.js -o main.js
